name: Build and Release FAP

on:
  push:
    branches:
      - main # Adjust this to your preference, e.g., releases/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure tags are fetched

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Set up the python version

    - name: Build Flipper Application Package (.fap)
      uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
      # Add any required inputs for flipperzero-ufbt-action here

    - name: Create Tag and Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own
      with:
        tag_name: ${{ github.ref }}-fap # or any other tag format you prefer
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step
        asset_path: ./dist/yuricable_pro_max.fap # You need to specify the path to your .fap file
        asset_name: yuricable_pro_max.fap # This will be the name of the asset as seen by users
        asset_content_type: application/octet-stream

            
