name: Build and Release FAP

on:
   push:
      tags:
         - 'v*.*.*'

permissions:
   contents: write

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
           include:
             - name: dev channel
               sdk-channel: dev
             - name: release channel
               sdk-channel: release
             - name: Momentum firmware
               sdk-index-url: https://up.momentum-fw.dev/firmware/directory.json
               sdk-channel: release
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0
              lfs: true

         - name: Setup Python
           uses: actions/setup-python@v4
           with:
              python-version: '3.11' # Set up the Python version

         - name: 'ufbt: Build for ${{ matrix.name }}'
           uses: flipperdevices/flipperzero-ufbt-action@v0.1
           id: build-app
           with:
             sdk-channel: ${{ matrix.sdk-channel }}
             sdk-index-url: ${{ matrix.sdk-index-url }}
         
         
         #- name: Build Flipper Application Package (.fap)
         #  uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
         #  id: build-app
           #with:
           #  sdk-branch: 0.97.1

         - name: Upload app artifacts
           uses: actions/upload-artifact@v3
           with:
              name: ${{ github.event.repository.name }}-${{ matrix.name }}-${{ steps.build-app.outputs.suffix }}
              path: ${{ steps.build-app.outputs.fap-artifacts }}

         # Release step
         - name: Create GitHub Release and Upload FAP
           uses: softprops/action-gh-release@v1
           if: startsWith(github.ref, 'refs/tags/') # Ensures this step only runs for tag pushes
           with:
              files: ${{ steps.build-app.outputs.fap-artifacts }}
              name: ${{ github.event.repository.name }}-${{ matrix.name }}-${{ steps.build-app.outputs.suffix }}.fap
              # Add other configuration options as needed, like body, name, draft, prerelease, etc.
