name: "FAP: Build and lint"
on: [push, pull_request]
jobs:
  fix-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ufbt
        run: |
          python -m pip install --upgrade pip
          pip install ufbt==latest # Specify the version you need

      - name: Run ufbt vscode_dist
        run: ufbt vscode_dist
        # Add any additional arguments here if necessary

      # Example for building with ufbt, adjust according to your needs
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          task: build
          sdk-channel: dev # Or any other SDK source you're using
          # Add other inputs as per your requirement

      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}

